// const questionsData = [
//   // --- Week 1 Questions ---
//   {
//     week: 1,
//     questionNumber: 1,
//     text: "Response of the organism or system to various stimuli or inputs, whether internal or external, conscious or subconscious, overt or covert, voluntary or involuntary is called:",
//     options: ["Organization", "Behaviour", "Resource", "Productivity"],
//     correctAnswer: "Behaviour",
//     points: 1,
//   },
//   {
//     week: 1,
//     questionNumber: 2,
//     text: "Which of the following is not an organization?",
//     options: ["TATA Steels", "UNICEF", "Facebook Inc.", "Germany"],
//     correctAnswer: "Germany",
//     points: 1,
//   },
//   {
//     week: 1,
//     questionNumber: 3,
//     text: "More output for less input or being able to provide optimal output for a given input is called:",
//     options: ["Effectiveness", "Productivity", "Efficiency", "Motivation"],
//     correctAnswer: "Efficiency",
//     points: 1,
//   },
//   {
//     week: 1,
//     questionNumber: 4,
//     text: "The social expectation on an individual is called:",
//     options: ["Role", "Designation", "Job", "Task"],
//     correctAnswer: "Role",
//     points: 1,
//   },
//   {
//     week: 1,
//     questionNumber: 5,
//     text: "Which field can be called as the mother of Organizational behaviour?",
//     options: ["Anthropology", "Economics", "Industrial Psychology", "Law"],
//     correctAnswer: "Industrial Psychology",
//     points: 1,
//   },
//   {
//     week: 1,
//     questionNumber: 6,
//     text: "The scientific management movement was pioneered by:",
//     options: ["Walter Dill Scott", "Edward K Strong Jr.", "Hugo Munsterberg", "Frederick W Taylor"],
//     correctAnswer: "Frederick W Taylor",
//     points: 1,
//   },
//   {
//     week: 1,
//     questionNumber: 7,
//     text: "The assembly line of production was first introduced by Henry Ford.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },
//   {
//     week: 1,
//     questionNumber: 8,
//     text: "The process of breaking down the entire job into specific tasks and see how each of these tasks are performed and how much time on an average a person will take to finish it is called:",
//     options: ["Time and Motion Study", "Workplace management", "Job Profile", "Productivity"],
//     correctAnswer: "Time and Motion Study",
//     points: 1,
//   },
//   {
//     week: 1,
//     questionNumber: 9,
//     text: "In an experiment, the group in which you make no changes is called the:",
//     options: ["Experimental Group", "Focus Group", "Control Group", "Target Group"],
//     correctAnswer: "Control Group",
//     points: 1,
//   },
//   {
//     week: 1,
//     questionNumber: 10,
//     text: "Hawthorne experiments were a set of experiments conducted to study the impact of assembly line on the health of the workers.",
//     options: ["True", "False"],
//     correctAnswer: "False",
//     points: 1,
//   },

//   // --- Week 2 Questions ---
//   {
//     week: 2,
//     questionNumber: 1,
//     text: "The process of giving meaning to sensory stimuli through organizing and interpreting is called:",
//     options: ["Sensation", "Perception", "Sublimation", "Organization"],
//     correctAnswer: "Perception",
//     points: 1,
//   },
//   {
//     week: 2,
//     questionNumber: 2,
//     text: "Perception is highly objective.",
//     options: ["True", "False"],
//     correctAnswer: "False",
//     points: 1,
//   },
//   {
//     week: 2,
//     questionNumber: 3,
//     text: "Which of the following is an internal factor that influence the principles of perceptual selection?",
//     options: ["Contrast", "Repetition", "Motion", "Habit"],
//     correctAnswer: "Habit",
//     points: 1,
//   },
//   {
//     week: 2,
//     questionNumber: 4,
//     text: "In the below picture, we tend to see columns of dots due to a perceptual grouping effect called: (Imagine dots arranged in a grid, forming columns)",
//     options: ["Similarity", "Proximity", "Continuity", "Symmetry"],
//     correctAnswer: "Proximity",
//     points: 1,
//     // imageUrl: "/assets/images/week2_q4.png" // Example for actual image path
//   },
//   {
//     week: 2,
//     questionNumber: 5,
//     text: "In the below image, one can still perceive the opening door to be of a rectangle shape due to: (Imagine an image of open doors)",
//     options: ["Figure-Ground Perception", "Optical Illusions", "Perceptual Constancy", "Social Perception"],
//     correctAnswer: "Perceptual Constancy",
//     points: 1,
//     // imageUrl: "/assets/images/week2_q5.png" // Example for actual image path
//   },
//   {
//     week: 2,
//     questionNumber: 6,
//     text: "According to Kelley's theory of causal attribution, the extent to which other people behave in the same manner as the person we are judging is called:",
//     options: ["Consensus", "Consistency", "Distinctiveness", "Identity"],
//     correctAnswer: "Consensus",
//     points: 1,
//   },
//   {
//     week: 2,
//     questionNumber: 7,
//     text: "The tendency to attribute others' action to internal causes while largely ignoring external factors is called:",
//     options: ["Halo effect", "Team-Halo effect", "Fundamental attribution error", "Similar-to-me effect"],
//     correctAnswer: "Fundamental attribution error",
//     points: 1,
//   },
//   {
//     week: 2,
//     questionNumber: 8,
//     text: "The word \"Carpenter\" immediately brings in to memory the image of a male individual rather than a female individual. This is an example of a job stereotype.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },
//   {
//     week: 2,
//     questionNumber: 9,
//     text: "There are many women at the bottom and middle level management roles but only a very few make it to the top. This is due to:",
//     options: ["Impression Management techniques", "Golem effect", "Pygmalion effect", "Glass-ceiling effect"],
//     correctAnswer: "Glass-ceiling effect",
//     points: 1,
//   },
//   {
//     week: 2,
//     questionNumber: 10,
//     text: "The process through which individuals attempt to determine the causes behind others' behaviour is called attribution.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },

//   // --- Week 3 Questions ---
//   {
//     week: 3,
//     questionNumber: 1,
//     text: "The meaning of the Latin word 'Persona' from which the word Personality arises is:",
//     options: ["Behaviour", "Mask", "Thought", "Person"],
//     correctAnswer: "Mask",
//     points: 1,
//   },
//   {
//     week: 3,
//     questionNumber: 2,
//     text: "Many psychologists argue that one's personality can be changed over a period of time because those qualities are formed because of social factors.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },
//   {
//     week: 3,
//     questionNumber: 3,
//     text: "According to Sigmund Freud's psychoanalytic theory, the deepest level of consciousness is:",
//     options: ["Subconscious", "Conscious state", "Unconscious", "Awareness"],
//     correctAnswer: "Unconscious",
//     points: 1,
//   },
//   {
//     week: 3,
//     questionNumber: 4,
//     text: "According to Sigmund Freud, reality principle is followed by:",
//     options: ["Id", "Super Ego", "Dream", "Ego"],
//     correctAnswer: "Ego",
//     points: 1,
//   },
//   {
//     week: 3,
//     questionNumber: 5,
//     text: "In social learning theory, the withdrawal of something which somebody likes to strengthen a behaviour is called:",
//     options: ["Negative Reinforcement", "Positive Reinforcement", "Reward", "Punishment"],
//     correctAnswer: "Negative Reinforcement",
//     points: 1,
//   },
//   {
//     week: 3,
//     questionNumber: 6,
//     text: "The main proponent of Self Theory was:",
//     options: ["Sigmund Freud", "Albert Bandura", "Carl Rogers", "B.F. Skinner"],
//     correctAnswer: "Carl Rogers",
//     points: 1,
//   },
//   {
//     week: 3,
//     questionNumber: 7,
//     text: "In Johari's Window model of self-awareness, the part of the self which is not known to ourselves, but others know is called:",
//     options: ["Open", "Blind", "Hidden", "Unknown"],
//     correctAnswer: "Blind",
//     points: 1,
//   },
//   {
//     week: 3,
//     questionNumber: 8,
//     text: "Employees with high self-esteem are more ready to take responsibilities.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },
//   {
//     week: 3,
//     questionNumber: 9,
//     text: "People with _______ locus of control believe that others control their life and whatever happens in their life is because of outside factors.",
//     options: ["Internal", "External"],
//     correctAnswer: "External",
//     points: 1,
//   },
//   {
//     week: 3,
//     questionNumber: 10,
//     text: "According to Big Five Personality Theory, people who like to experiment and try and find out new things and are less judgmental about people of other cultures are high on:",
//     options: ["Adjustment", "Agreeableness", "Conscientiousness", "Intellectual Openness"],
//     correctAnswer: "Intellectual Openness",
//     points: 1,
//   },

//   // --- Week 4 Questions ---
//   {
//     week: 4,
//     questionNumber: 1,
//     text: "A relatively permanent change in behaviour occurring as a result of experience is called:",
//     options: ["Thinking", "Sensation", "Learning", "Prejudice"],
//     correctAnswer: "Learning",
//     points: 1,
//   },
//   {
//     week: 4,
//     questionNumber: 2,
//     text: "In Pavlov's Dog experiment, the food presented which makes the dog salivate is:",
//     options: ["Unconditional stimulus", "Unconditional response", "Conditioned stimulus", "Conditioned response"],
//     correctAnswer: "Unconditional stimulus",
//     points: 1,
//   },
//   {
//     week: 4,
//     questionNumber: 3,
//     text: "In Operant conditioning, the process through which the responses that are no longer reinforced tend to gradually diminish in strength is called:",
//     options: ["Positive reinforcement", "Negative Reinforcement", "Punishment", "Extinction"],
//     correctAnswer: "Extinction",
//     points: 1,
//   },
//   {
//     week: 4,
//     questionNumber: 4,
//     text: "After watching a Dance TV show, a kid starts to make dance moves. This is an example of:",
//     options: ["Operant conditioning", "Classical conditioning", "Observational learning", "Negative Reinforcement"],
//     correctAnswer: "Observational learning",
//     points: 1,
//   },
//   {
//     week: 4,
//     questionNumber: 5,
//     text: "_______ are evaluative statements towards objects, people or events.",
//     options: ["Learning", "Attitudes", "Memory", "Personality"],
//     correctAnswer: "Attitudes",
//     points: 1,
//   },
//   {
//     week: 4,
//     questionNumber: 6,
//     text: "Opinion is primarily _______ in nature.",
//     options: ["Affective", "Cognitive", "Behavioural", "Unconscious"],
//     correctAnswer: "Cognitive",
//     points: 1,
//   },
//   {
//     week: 4,
//     questionNumber: 7,
//     text: "The intensity of an attitude or the magnitude/degree of its favorableness is called:",
//     options: ["Multiplexity", "Relation to need", "Centrality", "Valence"],
//     correctAnswer: "Valence",
//     points: 1,
//   },
//   {
//     week: 4,
//     questionNumber: 8,
//     text: "When people do not provide honest answers to certain questions because they feel that it is not right to give those answers, it is called:",
//     options: ["Social Loafing", "Fatigue", "Social Desirability Effect", "Sampling"],
//     correctAnswer: "Social Desirability Effect",
//     points: 1,
//   },
//   {
//     week: 4,
//     questionNumber: 9,
//     text: "Uncomfortable tension which comes from holding two conflicting thoughts in the mind at the same time is called Cognitive Dissonance.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },
//   {
//     week: 4,
//     questionNumber: 10,
//     text: "Providing more information can lead to change in attitude.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },

//   // --- Week 5 Questions ---
//   {
//     week: 5,
//     questionNumber: 1,
//     text: "An unfocused, relatively mild feeling that exists as background to our daily experience is called:",
//     options: ["Behaviour", "Perception", "Mood", "Envy"],
//     correctAnswer: "Mood",
//     points: 1,
//   },
//   {
//     week: 5,
//     questionNumber: 2,
//     text: "The psychological effort involved in holding back one's true emotions is called:",
//     options: ["Emotional dissonance", "Emotional labor", "Emotional Attachment", "Temperament"],
//     correctAnswer: "Emotional labor",
//     points: 1,
//   },
//   {
//     week: 5,
//     questionNumber: 3,
//     text: "When John failed his driving license test, he starts to remember how his friends used to tease him saying he was not a good driver. This is an example of:",
//     options: ["Work-family spillover effect", "Emotional dissonance", "Empathy", "Mood congruence effect"],
//     correctAnswer: "Mood congruence effect",
//     points: 1,
//   },
//   {
//     week: 5,
//     questionNumber: 4,
//     text: "_______ is a mild form of hate.",
//     options: ["Guilt", "Humiliation", "Resentment", "Shame"],
//     correctAnswer: "Resentment",
//     points: 1,
//   },
//   {
//     week: 5,
//     questionNumber: 5,
//     text: "Threat-based aggression can stem from both a real stimulus or a perceived stimulus.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },
//   {
//     week: 5,
//     questionNumber: 6,
//     text: "_______ is when you have a goal and you are moving towards that goal and you feel that something or someone is stopping you from reaching that goal.",
//     options: ["Threat-based aggression", "Instrumental aggression", "Irritable aggression", "Frustration-based aggression"],
//     correctAnswer: "Frustration-based aggression",
//     points: 1,
//   },
//   {
//     week: 5,
//     questionNumber: 7,
//     text: "Fear of being rejected is one of the main reasons that make people non-assertive.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },
//   {
//     week: 5,
//     questionNumber: 8,
//     text: "The stress which happens because of positive incidences is called:",
//     options: ["Distress", "Eustress", "Hypo-stress", "Hyper work stress"],
//     correctAnswer: "Eustress",
//     points: 1,
//   },
//   {
//     week: 5,
//     questionNumber: 9,
//     text: "The feeling of completely tired and exhausted when you are stressed for a very long time accompanied by lack of meaning is called:",
//     options: ["Burnout", "Absenteeism", "Hypo stress", "Alarm-reaction"],
//     correctAnswer: "Burnout",
//     points: 1,
//   },
//   {
//     week: 5,
//     questionNumber: 10,
//     text: "What are the behavioural symptoms of stress?",
//     options: ["Low productivity", "Interpersonal conflicts", "Suicidal tendencies", "All of the above"],
//     correctAnswer: "All of the above",
//     points: 1,
//   },

//   // --- Week 6 Questions ---
//   {
//     week: 6,
//     questionNumber: 1,
//     text: "The need to be part of a group is categorized as:",
//     options: ["Achievement motive", "Affiliation motive", "Power motive", "Role conflict"],
//     correctAnswer: "Affiliation motive",
//     points: 1,
//   },
//   {
//     week: 6,
//     questionNumber: 2,
//     text: "John had applied for several jobs after graduation. One day he received a job offer from Tata Motors and Mahindra Group, both of which he loved to work. The conflict Mr. John is facing in selecting one job is called:",
//     options: ["Role Conflict", "Approach-avoidance conflict", "Approach-approach conflict", "Avoidance-avoidance conflict"],
//     correctAnswer: "Approach-approach conflict",
//     points: 1,
//   },
//   {
//     week: 6,
//     questionNumber: 3,
//     text: "Money is a form of extrinsic motivation.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },
//   {
//     week: 6,
//     questionNumber: 4,
//     text: "According to Maslow's hierarchy of needs, the highest level of needs one can achieve is:",
//     options: ["Self-actualization", "Social Needs", "Esteem needs", "Safety needs"],
//     correctAnswer: "Self-actualization",
//     points: 1,
//   },
//   {
//     week: 6,
//     questionNumber: 5,
//     text: "According to Herzberg's two-factor theory of motivation, pay and security provided by a job is a Motivator.",
//     options: ["True", "False"],
//     correctAnswer: "False",
//     points: 1,
//   },
//   {
//     week: 6,
//     questionNumber: 6,
//     text: "In Alderfer's ERG theory of motivation, R stands for:",
//     options: ["Reputation", "Regression", "Resilience", "Relatedness"],
//     correctAnswer: "Relatedness",
//     points: 1,
//   },
//   {
//     week: 6,
//     questionNumber: 7,
//     text: "_______ means that employees feel that the organization treats its employees in a fair manner and a just way.",
//     options: ["Intra-personal conflict", "Self-esteem", "Power motive", "Organizational Justice Climate"],
//     correctAnswer: "Organizational Justice Climate",
//     points: 1,
//   },
//   {
//     week: 6,
//     questionNumber: 8,
//     text: "_______ is when you are moving towards a certain goal, but certain barriers are stopping you from achieving that goal.",
//     options: ["Goal conflict", "Role conflict", "Frustration", "Satisfaction"],
//     correctAnswer: "Frustration",
//     points: 1,
//   },
//   {
//     week: 6,
//     questionNumber: 9,
//     text: "_______ is the willingness of a person to put high levels of efforts to reach a goal.",
//     options: ["Emotions", "Motivation", "Frustration", "Incentives"],
//     correctAnswer: "Motivation",
//     points: 1,
//   },
//   {
//     week: 6,
//     questionNumber: 10,
//     text: "One of the drawbacks of using money as a motivator is that it can reduce extra-role performance.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },

//   // --- Week 7 Questions ---
//   {
//     week: 7,
//     questionNumber: 1,
//     text: "The degree of confidence we have on others in a relationship is called:",
//     options: ["Transactional contract", "Relational contract", "Trust", "Norms"],
//     correctAnswer: "Trust",
//     points: 1,
//   },
//   {
//     week: 7,
//     questionNumber: 2,
//     text: "The kind of psychological contract that focuses on long-term interaction and a widely defined relationship is called relational contract.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },
//   {
//     week: 7,
//     questionNumber: 3,
//     text: "The type of trust that is established based on the credibility of a person, for e.g., trusting the doctor:",
//     options: ["Trust based on familiarity", "Swift trust", "Trust based on similarity", "Trust based on social networks"],
//     correctAnswer: "Swift trust",
//     points: 1,
//   },
//   {
//     week: 7,
//     questionNumber: 4,
//     text: "The characteristic of being respectful towards others is:",
//     options: ["Conscientiousness", "Sportsmanship", "Civic virtue", "Courtesy"],
//     correctAnswer: "Courtesy",
//     points: 1,
//   },
//   {
//     week: 7,
//     questionNumber: 5,
//     text: "Treating the common resources responsibly is called civic virtue.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },
//   {
//     week: 7,
//     questionNumber: 6,
//     text: "_______ is helping without expecting anything in return.",
//     options: ["Altruism", "Competition", "Cooperation", "Conscientiousness"],
//     correctAnswer: "Altruism",
//     points: 1,
//   },
//   {
//     week: 7,
//     questionNumber: 7,
//     text: "When each party involved in a task tries to maximize its own gains, often at the expense of others, it is called:",
//     options: ["Cooperation", "Interdependency", "Competition", "None of the above"],
//     correctAnswer: "Competition",
//     points: 1,
//   },
//   {
//     week: 7,
//     questionNumber: 8,
//     text: "People who focus on maximizing the joint outcomes of everyone involved are called:",
//     options: ["Competitors", "Cooperators", "Individualists", "Equalizers"],
//     correctAnswer: "Cooperators",
//     points: 1,
//   },
//   {
//     week: 7,
//     questionNumber: 9,
//     text: "Which conflict handling style is best for both the parties involved?",
//     options: ["Competing", "Avoiding", "Accommodating", "Collaborating"],
//     correctAnswer: "Collaborating",
//     points: 1,
//   },
//   {
//     week: 7,
//     questionNumber: 10,
//     text: "Disagreements on strategy and sharing of responsibility and resources is called:",
//     options: ["Relational conflict", "Task conflict", "Process conflict", "Avoiding"],
//     correctAnswer: "Process conflict",
//     points: 1,
//   },

//   // --- Week 8 Questions ---
//   {
//     week: 8,
//     questionNumber: 1,
//     text: "In communication, the process of converting a message into symbols is called:",
//     options: ["Message", "Channel", "Decoding", "Encoding"],
//     correctAnswer: "Encoding",
//     points: 1,
//   },
//   {
//     week: 8,
//     questionNumber: 2,
//     text: "Any disturbance that interfere with the transmission, receipt or feedback of a message is called noise.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },
//   {
//     week: 8,
//     questionNumber: 3,
//     text: "The communication style that is supportive and avoids change and confrontation is called:",
//     options: ["Animated communication style", "Driver communication style", "Amiable communication style", "Analytical communication style"],
//     correctAnswer: "Amiable communication style",
//     points: 1,
//   },
//   {
//     week: 8,
//     questionNumber: 4,
//     text: "Which of the following is NOT a non-verbal mode of communication?",
//     options: ["Facial expressions", "Pupil dilation", "Gestures", "None of the above"],
//     correctAnswer: "None of the above", // All listed are non-verbal. So, "None of the above" is the correct choice if the question asks for NOT a non-verbal.
//     points: 1,
//   },
//   {
//     week: 8,
//     questionNumber: 5,
//     text: "The study of spatial inter-relationships is called:",
//     options: ["Kinesics", "Proxemics", "Silence", "Symbols"],
//     correctAnswer: "Proxemics",
//     points: 1,
//   },
//   {
//     week: 8,
//     questionNumber: 6,
//     text: "Maintaining and distributing minutes of the meeting is helpful in reducing miscommunication in team meetings.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },
//   {
//     week: 8,
//     questionNumber: 7,
//     text: "When parts of some information are shared with the group members whereas other pieces of information are unshared, it gives rise to:",
//     options: ["Hidden profile paradigm", "Awareness", "Trust building", "Minimizing status difference"],
//     correctAnswer: "Hidden profile paradigm",
//     points: 1,
//   },
//   {
//     week: 8,
//     questionNumber: 8,
//     text: "In information sharing scenario, the case that has to be avoided to reduce decision making problems is:",
//     options: ["Fully shared case", "Non-overlapping case", "Distributed partial overlap", "All of the above"],
//     correctAnswer: "Distributed partial overlap", // Based on the score 0, accepted answers was Distributed partial overlap
//     points: 1, // Note: OCR shows score 0, Accepted: Distributed partial overlap
//   },
//   {
//     week: 8,
//     questionNumber: 9,
//     text: "Most eastern cultures are comfortable with silence between conversations.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },
//   {
//     week: 8,
//     questionNumber: 10,
//     text: "The level of openness which exists in an organization which gives a certain level of comfort to its members is called:",
//     options: ["Common information effect", "Hidden profile paradigm", "Communication climate", "Paralinguistic communication"],
//     correctAnswer: "Communication climate",
//     points: 1,
//   },

//   // --- Week 9 Questions ---
//   {
//     week: 9,
//     questionNumber: 1,
//     text: "Making the smallest response possible that will reduce the problem to at least a tolerable level is called _______ to decision making.",
//     options: ["Satisficing approach", "Rational Approach", "Incremental approach", "Garbage-can approach"],
//     correctAnswer: "Incremental approach",
//     points: 1,
//   },
//   {
//     week: 9,
//     questionNumber: 2,
//     text: "Having a false sense of satisfaction even when problems start to show up is called:",
//     options: ["Complacency", "Procrastination", "Defensive avoidance", "Panic"],
//     correctAnswer: "Complacency",
//     points: 1,
//   },
//   {
//     week: 9,
//     questionNumber: 3,
//     text: "Trying to put the responsibility for decision making on somebody else is called buck passing.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },
//   {
//     week: 9,
//     questionNumber: 4,
//     text: "The tendency to be influenced by an initial figure, even when the information is largely irrelevant is called:",
//     options: ["Availability bias", "Overconfidence", "Anchoring and adjustment bias", "Representativeness"],
//     correctAnswer: "Anchoring and adjustment bias",
//     points: 1,
//   },
//   {
//     week: 9,
//     questionNumber: 5,
//     text: "The group's emphasis on harmony and conformity leading to a wrong decision is called:",
//     options: ["Majority rule", "Synergy", "Risk taking in groups", "Groupthink"],
//     correctAnswer: "Groupthink",
//     points: 1,
//   },
//   {
//     week: 9,
//     questionNumber: 6,
//     text: "Sunk costs can be recovered.",
//     options: ["True", "False"],
//     correctAnswer: "False",
//     points: 1,
//   },
//   {
//     week: 9,
//     questionNumber: 7,
//     text: "Tendency to invest additional resources in an apparently losing proposition, influenced by effort, money and time already invested:",
//     options: ["Abilene Paradox", "Delphi method", "Escalation of commitment", "Groupthink"],
//     correctAnswer: "Escalation of commitment",
//     points: 1,
//   },
//   {
//     week: 9,
//     questionNumber: 8,
//     text: "The step in team decision making where the problem is defined and a consensus is arrived about what the problem is:",
//     options: ["Discussion", "Implementation", "Representativeness", "Orientation"],
//     correctAnswer: "Orientation",
//     points: 1,
//   },
//   {
//     week: 9,
//     questionNumber: 9,
//     text: "The tendency to make different decisions depending on how a problem is presented:",
//     options: ["Framing", "Prospect theory", "Representativeness", "Bounded rationality"],
//     correctAnswer: "Framing",
//     points: 1,
//   },
//   {
//     week: 9,
//     questionNumber: 10,
//     text: "Finding a solution which is satisfactory than optimal is called satisficing approach to decision making.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },

//   // --- Week 10 Questions ---
//   {
//     week: 10,
//     questionNumber: 1,
//     text: "The source of power which is based on the capacity to administer punishment to others:",
//     options: ["Legitimate", "Reward", "Coercive", "Expert"],
//     correctAnswer: "Coercive",
//     points: 1,
//   },
//   {
//     week: 10,
//     questionNumber: 2,
//     text: "Expert power is when you have certain abilities which nobody else has or is very rare.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },
//   {
//     week: 10,
//     questionNumber: 3,
//     text: "Information one possesses, which cannot be recorded or measured is called:",
//     options: ["Empowerment", "Referent power", "Gossiping", "Tacit knowledge"],
//     correctAnswer: "Tacit knowledge",
//     points: 1,
//   },
//   {
//     week: 10,
//     questionNumber: 4,
//     text: "The form of political behaviour exhibited when employees try to form a group based on common language they speak is:",
//     options: ["Impression management", "Building coalitions", "Blaming", "Manipulating information flow"],
//     correctAnswer: "Building coalitions",
//     points: 1,
//   },
//   {
//     week: 10,
//     questionNumber: 5,
//     text: "_______ is the ability to persuade others to seek defined objectives enthusiastically.",
//     options: ["Coercion", "Behavioural change", "Leadership", "Authority"],
//     correctAnswer: "Leadership",
//     points: 1,
//   },
//   {
//     week: 10,
//     questionNumber: 6,
//     text: "While managers rely on control, leaders _______.",
//     options: ["Ask how and when", "Focus on systems and structure", "Accept status quo", "Inspire trust"],
//     correctAnswer: "Inspire trust",
//     points: 1,
//   },
//   {
//     week: 10,
//     questionNumber: 7,
//     text: "The leadership style where the responsibilities are shared by all and can be very useful in businesses where creative ideas are very important:",
//     options: ["Autocratic", "Laissez-Faire", "Task centered", "Paternalistic"],
//     correctAnswer: "Laissez-Faire",
//     points: 1,
//   },
//   {
//     week: 10,
//     questionNumber: 8,
//     text: "Democratic leadership style encourages decision making from different perspectives.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },
//   {
//     week: 10,
//     questionNumber: 9,
//     text: "The ideal case in Blake Mouton Managerial Grid of Leadership style is:",
//     options: ["Country club", "Impoverished", "Produce or perish", "Team Leader"],
//     correctAnswer: "Team Leader",
//     points: 1,
//   },
//   {
//     week: 10,
//     questionNumber: 10,
//     text: "The theory which states that the subordinates will be motivated to follow the leader only when they perceive that the leader can help them to fulfil their goals:",
//     options: ["Path-goal theory", "Fiedler's model", "Hersey and Blanchard's situational leadership theory", "Trait theory"],
//     correctAnswer: "Path-goal theory",
//     points: 1,
//   },

//   // --- Week 11 Questions ---
//   {
//     week: 11,
//     questionNumber: 1,
//     text: "Airline attendant teams are an example of:",
//     options: ["Production teams", "Service teams", "Advisory teams", "Management teams"],
//     correctAnswer: "Service teams",
//     points: 1,
//   },
//   {
//     week: 11,
//     questionNumber: 2,
//     text: "Groups are more cohesive than teams and groups are a subset of teams.",
//     options: ["True", "False"],
//     correctAnswer: "False",
//     points: 1,
//   },
//   {
//     week: 11,
//     questionNumber: 3,
//     text: "The stage of group development at which unwritten rules for teams are established:",
//     options: ["Norming", "Storming", "Forming", "Adjourning"],
//     correctAnswer: "Norming",
//     points: 1,
//   },
//   {
//     week: 11,
//     questionNumber: 4,
//     text: "Taking advantage of other members in a group and claiming ownership for their work is called:",
//     options: ["Altruism", "Groupthink", "Freeriding", "Synergy"],
//     correctAnswer: "Freeriding",
//     points: 1,
//   },
//   {
//     week: 11,
//     questionNumber: 5,
//     text: "Sometimes in teams, people may think that if they work more, other people will take advantage of them and give all the responsibilities to them. So it is better to decrease their performance. This phenomenon is called:",
//     options: ["De-individualization", "Social loafing", "Freeriding", "Sucker aversion"],
//     correctAnswer: "Sucker aversion",
//     points: 1,
//   },
//   {
//     week: 11,
//     questionNumber: 6,
//     text: "Low trust among the team members can often lead to social loafing.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },
//   {
//     week: 11,
//     questionNumber: 7,
//     text: "A type of thought exhibited by group members who try to minimize conflict and reach consensus without critically testing, analyzing and evaluating ideas.",
//     options: ["Team cohesion", "Instrumentality", "Mundane task", "Groupthink"],
//     correctAnswer: "Groupthink",
//     points: 1,
//   },
//   {
//     week: 11,
//     questionNumber: 8,
//     text: "Culture influences both the conscious and unconscious level of the mind.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },
//   {
//     week: 11,
//     questionNumber: 9,
//     text: "An organization in which its culture is driven by the motive for affiliation:",
//     options: ["Bureaucracy", "Industrial Organization", "Clubs", "Educational Institutions"],
//     correctAnswer: "Clubs",
//     points: 1,
//   },
//   {
//     week: 11,
//     questionNumber: 10,
//     text: "Which of the following is the source of organizational culture?",
//     options: ["Selection practices", "Actions of top management", "Socialization methods", "Founder's vision/mission/attitudes"],
//     correctAnswer: "Founder's vision/mission/attitudes",
//     points: 1,
//   },

//   // --- Week 12 Questions ---
//   {
//     week: 12,
//     questionNumber: 1,
//     text: "Redesigning business processes to increase organizational effectiveness is called:",
//     options: ["Restructuring", "Reengineering", "Organizational Ethics", "Downsizing"],
//     correctAnswer: "Reengineering",
//     points: 1,
//   },
//   {
//     week: 12,
//     questionNumber: 2,
//     text: "Revolutionary change happens slowly in an organization and on its own.",
//     options: ["True", "False"],
//     correctAnswer: "False",
//     points: 1,
//   },
//   {
//     week: 12,
//     questionNumber: 3,
//     text: "The formal system of task and authority relationships that control how people coordinate their actions and use resources to achieve organizational goals is called:",
//     options: ["Organizational structure", "Organizational change", "Cognitive biases", "Resource allocation"],
//     correctAnswer: "Organizational structure",
//     points: 1,
//   },
//   {
//     week: 12,
//     questionNumber: 4,
//     text: "Indian Railways having different zones of operation like Southern Railways, Central Railway etc. is an example of:",
//     options: ["Horizontal differentiation", "Vertical differentiation", "Spatial differentiation", "None of the above"],
//     correctAnswer: "Spatial differentiation",
//     points: 1,
//   },
//   {
//     week: 12,
//     questionNumber: 5,
//     text: "Defining employees' roles through formal documentation is a part of formalization.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },
//   {
//     week: 12,
//     questionNumber: 6,
//     text: "_______ can provide more inputs into decision making and will help in reducing information overload.",
//     options: ["Centralization", "Decentralization", "Environmental uncertainty", "None of the above"],
//     correctAnswer: "Decentralization",
//     points: 1,
//   },
//   {
//     week: 12,
//     questionNumber: 7,
//     text: "According to life-cycle perspective, the stage of organizational life cycle where the goals are ambiguous but there is a lot of creativity is called:",
//     options: ["Formalization-and-control stage", "Collectivity stage", "Elaboration-of-structure stage", "Entrepreneurial stage"],
//     correctAnswer: "Entrepreneurial stage",
//     points: 1,
//   },
//   {
//     week: 12,
//     questionNumber: 8,
//     text: "The life-cycle perspective sees the organization as an organism.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },
//   {
//     week: 12,
//     questionNumber: 9,
//     text: "A set of interrelated and interdependent parts arranged in a manner that produces a unified whole is called:",
//     options: ["System", "Training", "Rituals", "Span of control"],
//     correctAnswer: "System",
//     points: 1,
//   },
//   {
//     week: 12,
//     questionNumber: 10,
//     text: "Closed systems differentiate too much from the larger system and have their own identity.",
//     options: ["True", "False"],
//     correctAnswer: "True",
//     points: 1,
//   },
// ];

// module.exports = questionsData;
const questionsData = [
  // --- Week 1 Questions ---
  {
    week: 1,
    questionNumber: 1,
    text: "Response of the organism or system to various stimuli or inputs, whether internal or external, conscious or subconscious, overt or covert, voluntary or involuntary is called:",
    options: ["Organization", "Behaviour", "Resource", "Productivity"],
    correctAnswer: "Behaviour",
    points: 1,
  },
  {
    week: 1,
    questionNumber: 2,
    text: "Which of the following is not an organization?",
    options: ["TATA Steels", "UNICEF", "Facebook Inc.", "Germany"],
    correctAnswer: "Germany",
    points: 1,
  },
  {
    week: 1,
    questionNumber: 3,
    text: "More output for less input or being able to provide optimal output for a given input is called:",
    options: ["Effectiveness", "Productivity", "Efficiency", "Motivation"],
    correctAnswer: "Efficiency",
    points: 1,
  },
  {
    week: 1,
    questionNumber: 4,
    text: "The social expectation on an individual is called:",
    options: ["Role", "Designation", "Job", "Task"],
    correctAnswer: "Role",
    points: 1,
  },
  {
    week: 1,
    questionNumber: 5,
    text: "Which field can be called as the mother of Organizational behaviour?",
    options: ["Anthropology", "Economics", "Industrial Psychology", "Law"],
    correctAnswer: "Industrial Psychology",
    points: 1,
  },
  {
    week: 1,
    questionNumber: 6,
    text: "The scientific management movement was pioneered by:",
    options: ["Walter Dill Scott", "Edward K Strong Jr.", "Hugo Munsterberg", "Frederick W Taylor"],
    correctAnswer: "Frederick W Taylor",
    points: 1,
  },
  {
    week: 1,
    questionNumber: 7,
    text: "The assembly line of production was first introduced by Henry Ford.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },
  {
    week: 1,
    questionNumber: 8,
    text: "The process of breaking down the entire job into specific tasks and see how each of these tasks are performed and how much time on an average a person will take to finish it is called:",
    options: ["Time and Motion Study", "Workplace management", "Job Profile", "Productivity"],
    correctAnswer: "Time and Motion Study",
    points: 1,
  },
  {
    week: 1,
    questionNumber: 9,
    text: "In an experiment, the group in which you make no changes is called the:",
    options: ["Experimental Group", "Focus Group", "Control Group", "Target Group"],
    correctAnswer: "Control Group",
    points: 1,
  },
  {
    week: 1,
    questionNumber: 10,
    text: "Hawthorne experiments were a set of experiments conducted to study the impact of assembly line on the health of the workers.",
    options: ["True", "False"],
    correctAnswer: "False",
    points: 1,
  },

  // --- Week 2 Questions ---
  {
    week: 2,
    questionNumber: 1,
    text: "The process of giving meaning to sensory stimuli through organizing and interpreting is called:",
    options: ["Sensation", "Perception", "Sublimation", "Organization"],
    correctAnswer: "Perception",
    points: 1,
  },
  {
    week: 2,
    questionNumber: 2,
    text: "Perception is highly objective.",
    options: ["True", "False"],
    correctAnswer: "False",
    points: 1,
  },
  {
    week: 2,
    questionNumber: 3,
    text: "Which of the following is an internal factor that influence the principles of perceptual selection?",
    options: ["Contrast", "Repetition", "Motion", "Habit"],
    correctAnswer: "Habit",
    points: 1,
  },
  {
    week: 2,
    questionNumber: 4,
    text: "In the below picture, we tend to see columns of dots due to a perceptual grouping effect called: (Imagine dots arranged in a grid, forming columns)",
    options: ["Similarity", "Proximity", "Continuity", "Symmetry"],
    correctAnswer: "Proximity",
    points: 1,
    // imageUrl: "/assets/images/week2_q4.png" // Example: If you have an image, place it in client/public/assets/images and provide the path
  },
  {
    week: 2,
    questionNumber: 5,
    text: "In the below image, one can still perceive the opening door to be of a rectangle shape due to: (Imagine an image of open doors)",
    options: ["Figure-Ground Perception", "Optical Illusions", "Perceptual Constancy", "Social Perception"],
    correctAnswer: "Perceptual Constancy",
    points: 1,
    // imageUrl: "/assets/images/week2_q5.png" // Example
  },
  {
    week: 2,
    questionNumber: 6,
    text: "According to Kelley's theory of causal attribution, the extent to which other people behave in the same manner as the person we are judging is called:",
    options: ["Consensus", "Consistency", "Distinctiveness", "Identity"],
    correctAnswer: "Consensus",
    points: 1,
  },
  {
    week: 2,
    questionNumber: 7,
    text: "The tendency to attribute others' action to internal causes while largely ignoring external factors is called:",
    options: ["Halo effect", "Team-Halo effect", "Fundamental attribution error", "Similar-to-me effect"],
    correctAnswer: "Fundamental attribution error",
    points: 1,
  },
  {
    week: 2,
    questionNumber: 8,
    text: "The word \"Carpenter\" immediately brings in to memory the image of a male individual rather than a female individual. This is an example of a job stereotype.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },
  {
    week: 2,
    questionNumber: 9,
    text: "There are many women at the bottom and middle level management roles but only a very few make it to the top. This is due to:",
    options: ["Impression Management techniques", "Golem effect", "Pygmalion effect", "Glass-ceiling effect"],
    correctAnswer: "Glass-ceiling effect",
    points: 1,
  },
  {
    week: 2,
    questionNumber: 10,
    text: "The process through which individuals attempt to determine the causes behind others' behaviour is called attribution.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },

  // --- Week 3 Questions ---
  {
    week: 3,
    questionNumber: 1,
    text: "The meaning of the Latin word 'Persona' from which the word Personality arises is:",
    options: ["Behaviour", "Mask", "Thought", "Person"],
    correctAnswer: "Mask",
    points: 1,
  },
  {
    week: 3,
    questionNumber: 2,
    text: "Many psychologists argue that one's personality can be changed over a period of time because those qualities are formed because of social factors.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },
  {
    week: 3,
    questionNumber: 3,
    text: "According to Sigmund Freud's psychoanalytic theory, the deepest level of consciousness is:",
    options: ["Subconscious", "Conscious state", "Unconscious", "Awareness"],
    correctAnswer: "Unconscious",
    points: 1,
  },
  {
    week: 3,
    questionNumber: 4,
    text: "According to Sigmund Freud, reality principle is followed by:",
    options: ["Id", "Super Ego", "Dream", "Ego"],
    correctAnswer: "Ego",
    points: 1,
  },
  {
    week: 3,
    questionNumber: 5,
    text: "In social learning theory, the withdrawal of something which somebody likes to strengthen a behaviour is called:",
    options: ["Negative Reinforcement", "Positive Reinforcement", "Reward", "Punishment"],
    correctAnswer: "Negative Reinforcement",
    points: 1,
  },
  {
    week: 3,
    questionNumber: 6,
    text: "The main proponent of Self Theory was:",
    options: ["Sigmund Freud", "Albert Bandura", "Carl Rogers", "B.F. Skinner"],
    correctAnswer: "Carl Rogers",
    points: 1,
  },
  {
    week: 3,
    questionNumber: 7,
    text: "In Johari's Window model of self-awareness, the part of the self which is not known to ourselves, but others know is called:",
    options: ["Open", "Blind", "Hidden", "Unknown"],
    correctAnswer: "Blind",
    points: 1,
  },
  {
    week: 3,
    questionNumber: 8,
    text: "Employees with high self-esteem are more ready to take responsibilities.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },
  {
    week: 3,
    questionNumber: 9,
    text: "People with _______ locus of control believe that others control their life and whatever happens in their life is because of outside factors.",
    options: ["Internal", "External"],
    correctAnswer: "External",
    points: 1,
  },
  {
    week: 3,
    questionNumber: 10,
    text: "According to Big Five Personality Theory, people who like to experiment and try and find out new things and are less judgmental about people of other cultures are high on:",
    options: ["Adjustment", "Agreeableness", "Conscientiousness", "Intellectual Openness"],
    correctAnswer: "Intellectual Openness",
    points: 1,
  },

  // --- Week 4 Questions ---
  {
    week: 4,
    questionNumber: 1,
    text: "A relatively permanent change in behaviour occurring as a result of experience is called:",
    options: ["Thinking", "Sensation", "Learning", "Prejudice"],
    correctAnswer: "Learning",
    points: 1,
  },
  {
    week: 4,
    questionNumber: 2,
    text: "In Pavlov's Dog experiment, the food presented which makes the dog salivate is:",
    options: ["Unconditional stimulus", "Unconditional response", "Conditioned stimulus", "Conditioned response"],
    correctAnswer: "Unconditional stimulus",
    points: 1,
  },
  {
    week: 4,
    questionNumber: 3,
    text: "In Operant conditioning, the process through which the responses that are no longer reinforced tend to gradually diminish in strength is called:",
    options: ["Positive reinforcement", "Negative Reinforcement", "Punishment", "Extinction"],
    correctAnswer: "Extinction",
    points: 1,
  },
  {
    week: 4,
    questionNumber: 4,
    text: "After watching a Dance TV show, a kid starts to make dance moves. This is an example of:",
    options: ["Operant conditioning", "Classical conditioning", "Observational learning", "Negative Reinforcement"],
    correctAnswer: "Observational learning",
    points: 1,
  },
  {
    week: 4,
    questionNumber: 5,
    text: "_______ are evaluative statements towards objects, people or events.",
    options: ["Learning", "Attitudes", "Memory", "Personality"],
    correctAnswer: "Attitudes",
    points: 1,
  },
  {
    week: 4,
    questionNumber: 6,
    text: "Opinion is primarily _______ in nature.",
    options: ["Affective", "Cognitive", "Behavioural", "Unconscious"],
    correctAnswer: "Cognitive",
    points: 1,
  },
  {
    week: 4,
    questionNumber: 7,
    text: "The intensity of an attitude or the magnitude/degree of its favorableness is called:",
    options: ["Multiplexity", "Relation to need", "Centrality", "Valence"],
    correctAnswer: "Valence",
    points: 1,
  },
  {
    week: 4,
    questionNumber: 8,
    text: "When people do not provide honest answers to certain questions because they feel that it is not right to give those answers, it is called:",
    options: ["Social Loafing", "Fatigue", "Social Desirability Effect", "Sampling"],
    correctAnswer: "Social Desirationality Effect", // Accepted answer from PDF: Social Desirability Effect
    points: 1,
  },
  {
    week: 4,
    questionNumber: 9,
    text: "Uncomfortable tension which comes from holding two conflicting thoughts in the mind at the same time is called Cognitive Dissonance.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },
  {
    week: 4,
    questionNumber: 10,
    text: "Providing more information can lead to change in attitude.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },

  // --- Week 5 Questions ---
  {
    week: 5,
    questionNumber: 1,
    text: "An unfocused, relatively mild feeling that exists as background to our daily experience is called:",
    options: ["Behaviour", "Perception", "Mood", "Envy"],
    correctAnswer: "Mood",
    points: 1,
  },
  {
    week: 5,
    questionNumber: 2,
    text: "The psychological effort involved in holding back one's true emotions is called:",
    options: ["Emotional dissonance", "Emotional labor", "Emotional Attachment", "Temperament"],
    correctAnswer: "Emotional labor",
    points: 1,
  },
  {
    week: 5,
    questionNumber: 3,
    text: "When John failed his driving license test, he starts to remember how his friends used to tease him saying he was not a good driver. This is an example of:",
    options: ["Work-family spillover effect", "Emotional dissonance", "Empathy", "Mood congruence effect"],
    correctAnswer: "Mood congruence effect",
    points: 1,
  },
  {
    week: 5,
    questionNumber: 4,
    text: "_______ is a mild form of hate.",
    options: ["Guilt", "Humiliation", "Resentment", "Shame"],
    correctAnswer: "Resentment",
    points: 1,
  },
  {
    week: 5,
    questionNumber: 5,
    text: "Threat-based aggression can stem from both a real stimulus or a perceived stimulus.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },
  {
    week: 5,
    questionNumber: 6,
    text: "_______ is when you have a goal and you are moving towards that goal and you feel that something or someone is stopping you from reaching that goal.",
    options: ["Threat-based aggression", "Instrumental aggression", "Irritable aggression", "Frustration-based aggression"],
    correctAnswer: "Frustration-based aggression",
    points: 1,
  },
  {
    week: 5,
    questionNumber: 7,
    text: "Fear of being rejected is one of the main reasons that make people non-assertive.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },
  {
    week: 5,
    questionNumber: 8,
    text: "The stress which happens because of positive incidences is called:",
    options: ["Distress", "Eustress", "Hypo-stress", "Hyper work stress"],
    correctAnswer: "Eustress",
    points: 1,
  },
  {
    week: 5,
    questionNumber: 9,
    text: "The feeling of completely tired and exhausted when you are stressed for a very long time accompanied by lack of meaning is called:",
    options: ["Burnout", "Absenteeism", "Hypo stress", "Alarm-reaction"],
    correctAnswer: "Burnout",
    points: 1,
  },
  {
    week: 5,
    questionNumber: 10,
    text: "What are the behavioural symptoms of stress?",
    options: ["Low productivity", "Interpersonal conflicts", "Suicidal tendencies", "All of the above"],
    correctAnswer: "All of the above",
    points: 1,
  },

  // --- Week 6 Questions ---
  {
    week: 6,
    questionNumber: 1,
    text: "The need to be part of a group is categorized as:",
    options: ["Achievement motive", "Affiliation motive", "Power motive", "Role conflict"],
    correctAnswer: "Affiliation motive",
    points: 1,
  },
  {
    week: 6,
    questionNumber: 2,
    text: "John had applied for several jobs after graduation. One day he received a job offer from Tata Motors and Mahindra Group, both of which he loved to work. The conflict Mr. John is facing in selecting one job is called:",
    options: ["Role Conflict", "Approach-avoidance conflict", "Approach-approach conflict", "Avoidance-avoidance conflict"],
    correctAnswer: "Approach-approach conflict",
    points: 1,
  },
  {
    week: 6,
    questionNumber: 3,
    text: "Money is a form of extrinsic motivation.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },
  {
    week: 6,
    questionNumber: 4,
    text: "According to Maslow's hierarchy of needs, the highest level of needs one can achieve is:",
    options: ["Self-actualization", "Social Needs", "Esteem needs", "Safety needs"],
    correctAnswer: "Self-actualization",
    points: 1,
  },
  {
    week: 6,
    questionNumber: 5,
    text: "According to Herzberg's two-factor theory of motivation, pay and security provided by a job is a Motivator.",
    options: ["True", "False"],
    correctAnswer: "False",
    points: 1,
  },
  {
    week: 6,
    questionNumber: 6,
    text: "In Alderfer's ERG theory of motivation, R stands for:",
    options: ["Reputation", "Regression", "Resilience", "Relatedness"],
    correctAnswer: "Relatedness",
    points: 1,
  },
  {
    week: 6,
    questionNumber: 7,
    text: "_______ means that employees feel that the organization treats its employees in a fair manner and a just way.",
    options: ["Intra-personal conflict", "Self-esteem", "Power motive", "Organizational Justice Climate"],
    correctAnswer: "Organizational Justice Climate",
    points: 1,
  },
  {
    week: 6,
    questionNumber: 8,
    text: "_______ is when you are moving towards a certain goal, but certain barriers are stopping you from achieving that goal.",
    options: ["Goal conflict", "Role conflict", "Frustration", "Satisfaction"],
    correctAnswer: "Frustration",
    points: 1,
  },
  {
    week: 6,
    questionNumber: 9,
    text: "_______ is the willingness of a person to put high levels of efforts to reach a goal.",
    options: ["Emotions", "Motivation", "Frustration", "Incentives"],
    correctAnswer: "Motivation",
    points: 1,
  },
  {
    week: 6,
    questionNumber: 10,
    text: "One of the drawbacks of using money as a motivator is that it can reduce extra-role performance.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },

  // --- Week 7 Questions ---
  {
    week: 7,
    questionNumber: 1,
    text: "The degree of confidence we have on others in a relationship is called:",
    options: ["Transactional contract", "Relational contract", "Trust", "Norms"],
    correctAnswer: "Trust",
    points: 1,
  },
  {
    week: 7,
    questionNumber: 2,
    text: "The kind of psychological contract that focuses on long-term interaction and a widely defined relationship is called relational contract.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },
  {
    week: 7,
    questionNumber: 3,
    text: "The type of trust that is established based on the credibility of a person, for e.g., trusting the doctor:",
    options: ["Trust based on familiarity", "Swift trust", "Trust based on similarity", "Trust based on social networks"],
    correctAnswer: "Swift trust",
    points: 1,
  },
  {
    week: 7,
    questionNumber: 4,
    text: "The characteristic of being respectful towards others is:",
    options: ["Conscientiousness", "Sportsmanship", "Civic virtue", "Courtesy"],
    correctAnswer: "Courtesy",
    points: 1,
  },
  {
    week: 7,
    questionNumber: 5,
    text: "Treating the common resources responsibly is called civic virtue.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },
  {
    week: 7,
    questionNumber: 6,
    text: "_______ is helping without expecting anything in return.",
    options: ["Altruism", "Competition", "Cooperation", "Conscientiousness"],
    correctAnswer: "Altruism",
    points: 1,
  },
  {
    week: 7,
    questionNumber: 7,
    text: "When each party involved in a task tries to maximize its own gains, often at the expense of others, it is called:",
    options: ["Cooperation", "Interdependency", "Competition", "None of the above"],
    correctAnswer: "Competition",
    points: 1,
  },
  {
    week: 7,
    questionNumber: 8,
    text: "People who focus on maximizing the joint outcomes of everyone involved are called:",
    options: ["Competitors", "Cooperators", "Individualists", "Equalizers"],
    correctAnswer: "Cooperators",
    points: 1,
  },
  {
    week: 7,
    questionNumber: 9,
    text: "Which conflict handling style is best for both the parties involved?",
    options: ["Competing", "Avoiding", "Accommodating", "Collaborating"],
    correctAnswer: "Collaborating",
    points: 1,
  },
  {
    week: 7,
    questionNumber: 10,
    text: "Disagreements on strategy and sharing of responsibility and resources is called:",
    options: ["Relational conflict", "Task conflict", "Process conflict", "Avoiding"],
    correctAnswer: "Process conflict",
    points: 1,
  },

  // --- Week 8 Questions ---
  {
    week: 8,
    questionNumber: 1,
    text: "In communication, the process of converting a message into symbols is called:",
    options: ["Message", "Channel", "Decoding", "Encoding"],
    correctAnswer: "Encoding",
    points: 1,
  },
  {
    week: 8,
    questionNumber: 2,
    text: "Any disturbance that interfere with the transmission, receipt or feedback of a message is called noise.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },
  {
    week: 8,
    questionNumber: 3,
    text: "The communication style that is supportive and avoids change and confrontation is called:",
    options: ["Animated communication style", "Driver communication style", "Amiable communication style", "Analytical communication style"],
    correctAnswer: "Amiable communication style",
    points: 1,
  },
  {
    week: 8,
    questionNumber: 4,
    text: "Which of the following is NOT a non-verbal mode of communication?",
    options: ["Facial expressions", "Pupil dilation", "Gestures", "None of the above"],
    correctAnswer: "None of the above",
    points: 1,
  },
  {
    week: 8,
    questionNumber: 5,
    text: "The study of spatial inter-relationships is called:",
    options: ["Kinesics", "Proxemics", "Silence", "Symbols"],
    correctAnswer: "Proxemics",
    points: 1,
  },
  {
    week: 8,
    questionNumber: 6,
    text: "Maintaining and distributing minutes of the meeting is helpful in reducing miscommunication in team meetings.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },
  {
    week: 8,
    questionNumber: 7,
    text: "When parts of some information are shared with the group members whereas other pieces of information are unshared, it gives rise to:",
    options: ["Hidden profile paradigm", "Awareness", "Trust building", "Minimizing status difference"],
    correctAnswer: "Hidden profile paradigm",
    points: 1,
  },
  {
    week: 8,
    questionNumber: 8,
    text: "In information sharing scenario, the case that has to be avoided to reduce decision making problems is:",
    options: ["Fully shared case", "Non-overlapping case", "Distributed partial overlap", "All of the above"],
    correctAnswer: "Distributed partial overlap",
    points: 1,
  },
  {
    week: 8,
    questionNumber: 9,
    text: "Most eastern cultures are comfortable with silence between conversations.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },
  {
    week: 8,
    questionNumber: 10,
    text: "The level of openness which exists in an organization which gives a certain level of comfort to its members is called:",
    options: ["Common information effect", "Hidden profile paradigm", "Communication climate", "Paralinguistic communication"],
    correctAnswer: "Communication climate",
    points: 1,
  },

  // --- Week 9 Questions ---
  {
    week: 9,
    questionNumber: 1,
    text: "Making the smallest response possible that will reduce the problem to at least a tolerable level is called _______ to decision making.",
    options: ["Satisficing approach", "Rational Approach", "Incremental approach", "Garbage-can approach"],
    correctAnswer: "Incremental approach",
    points: 1,
  },
  {
    week: 9,
    questionNumber: 2,
    text: "Having a false sense of satisfaction even when problems start to show up is called:",
    options: ["Complacency", "Procrastination", "Defensive avoidance", "Panic"],
    correctAnswer: "Complacency",
    points: 1,
  },
  {
    week: 9,
    questionNumber: 3,
    text: "Trying to put the responsibility for decision making on somebody else is called buck passing.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },
  {
    week: 9,
    questionNumber: 4,
    text: "The tendency to be influenced by an initial figure, even when the information is largely irrelevant is called:",
    options: ["Availability bias", "Overconfidence", "Anchoring and adjustment bias", "Representativeness"],
    correctAnswer: "Anchoring and adjustment bias",
    points: 1,
  },
  {
    week: 9,
    questionNumber: 5,
    text: "The group's emphasis on harmony and conformity leading to a wrong decision is called:",
    options: ["Majority rule", "Synergy", "Risk taking in groups", "Groupthink"],
    correctAnswer: "Groupthink",
    points: 1,
  },
  {
    week: 9,
    questionNumber: 6,
    text: "Sunk costs can be recovered.",
    options: ["True", "False"],
    correctAnswer: "False",
    points: 1,
  },
  {
    week: 9,
    questionNumber: 7,
    text: "Tendency to invest additional resources in an apparently losing proposition, influenced by effort, money and time already invested:",
    options: ["Abilene Paradox", "Delphi method", "Escalation of commitment", "Groupthink"],
    correctAnswer: "Escalation of commitment",
    points: 1,
  },
  {
    week: 9,
    questionNumber: 8,
    text: "The step in team decision making where the problem is defined and a consensus is arrived about what the problem is:",
    options: ["Discussion", "Implementation", "Representativeness", "Orientation"],
    correctAnswer: "Orientation",
    points: 1,
  },
  {
    week: 9,
    questionNumber: 9,
    text: "The tendency to make different decisions depending on how a problem is presented:",
    options: ["Framing", "Prospect theory", "Representativeness", "Bounded rationality"],
    correctAnswer: "Framing",
    points: 1,
  },
  {
    week: 9,
    questionNumber: 10,
    text: "Finding a solution which is satisfactory than optimal is called satisficing approach to decision making.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },

  // --- Week 10 Questions ---
  {
    week: 10,
    questionNumber: 1,
    text: "The source of power which is based on the capacity to administer punishment to others:",
    options: ["Legitimate", "Reward", "Coercive", "Expert"],
    correctAnswer: "Coercive",
    points: 1,
  },
  {
    week: 10,
    questionNumber: 2,
    text: "Expert power is when you have certain abilities which nobody else has or is very rare.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },
  {
    week: 10,
    questionNumber: 3,
    text: "Information one possesses, which cannot be recorded or measured is called:",
    options: ["Empowerment", "Referent power", "Gossiping", "Tacit knowledge"],
    correctAnswer: "Tacit knowledge",
    points: 1,
  },
  {
    week: 10,
    questionNumber: 4,
    text: "The form of political behaviour exhibited when employees try to form a group based on common language they speak is:",
    options: ["Impression management", "Building coalitions", "Blaming", "Manipulating information flow"],
    correctAnswer: "Building coalitions",
    points: 1,
  },
  {
    week: 10,
    questionNumber: 5,
    text: "_______ is the ability to persuade others to seek defined objectives enthusiastically.",
    options: ["Coercion", "Behavioural change", "Leadership", "Authority"],
    correctAnswer: "Leadership",
    points: 1,
  },
  {
    week: 10,
    questionNumber: 6,
    text: "While managers rely on control, leaders _______.",
    options: ["Ask how and when", "Focus on systems and structure", "Accept status quo", "Inspire trust"],
    correctAnswer: "Inspire trust",
    points: 1,
  },
  {
    week: 10,
    questionNumber: 7,
    text: "The leadership style where the responsibilities are shared by all and can be very useful in businesses where creative ideas are very important:",
    options: ["Autocratic", "Laissez-Faire", "Task centered", "Paternalistic"],
    correctAnswer: "Laissez-Faire",
    points: 1,
  },
  {
    week: 10,
    questionNumber: 8,
    text: "Democratic leadership style encourages decision making from different perspectives.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },
  {
    week: 10,
    questionNumber: 9,
    text: "The ideal case in Blake Mouton Managerial Grid of Leadership style is:",
    options: ["Country club", "Impoverished", "Produce or perish", "Team Leader"],
    correctAnswer: "Team Leader",
    points: 1,
  },
  {
    week: 10,
    questionNumber: 10,
    text: "The theory which states that the subordinates will be motivated to follow the leader only when they perceive that the leader can help them to fulfil their goals:",
    options: ["Path-goal theory", "Fiedler's model", "Hersey and Blanchard's situational leadership theory", "Trait theory"],
    correctAnswer: "Path-goal theory",
    points: 1,
  },

  // --- Week 11 Questions ---
  {
    week: 11,
    questionNumber: 1,
    text: "Airline attendant teams are an example of:",
    options: ["Production teams", "Service teams", "Advisory teams", "Management teams"],
    correctAnswer: "Service teams",
    points: 1,
  },
  {
    week: 11,
    questionNumber: 2,
    text: "Groups are more cohesive than teams and groups are a subset of teams.",
    options: ["True", "False"],
    correctAnswer: "False",
    points: 1,
  },
  {
    week: 11,
    questionNumber: 3,
    text: "The stage of group development at which unwritten rules for teams are established:",
    options: ["Norming", "Storming", "Forming", "Adjourning"],
    correctAnswer: "Norming",
    points: 1,
  },
  {
    week: 11,
    questionNumber: 4,
    text: "Taking advantage of other members in a group and claiming ownership for their work is called:",
    options: ["Altruism", "Groupthink", "Freeriding", "Synergy"],
    correctAnswer: "Freeriding",
    points: 1,
  },
  {
    week: 11,
    questionNumber: 5,
    text: "Sometimes in teams, people may think that if they work more, other people will take advantage of them and give all the responsibilities to them. So it is better to decrease their performance. This phenomenon is called:",
    options: ["De-individualization", "Social loafing", "Freeriding", "Sucker aversion"],
    correctAnswer: "Sucker aversion",
    points: 1,
  },
  {
    week: 11,
    questionNumber: 6,
    text: "Low trust among the team members can often lead to social loafing.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },
  {
    week: 11,
    questionNumber: 7,
    text: "A type of thought exhibited by group members who try to minimize conflict and reach consensus without critically testing, analyzing and evaluating ideas.",
    options: ["Team cohesion", "Instrumentality", "Mundane task", "Groupthink"],
    correctAnswer: "Groupthink",
    points: 1,
  },
  {
    week: 11,
    questionNumber: 8,
    text: "Culture influences both the conscious and unconscious level of the mind.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },
  {
    week: 11,
    questionNumber: 9,
    text: "An organization in which its culture is driven by the motive for affiliation:",
    options: ["Bureaucracy", "Industrial Organization", "Clubs", "Educational Institutions"],
    correctAnswer: "Clubs",
    points: 1,
  },
  {
    week: 11,
    questionNumber: 10,
    text: "Which of the following is the source of organizational culture?",
    options: ["Selection practices", "Actions of top management", "Socialization methods", "Founder's vision/mission/attitudes"],
    correctAnswer: "Founder's vision/mission/attitudes",
    points: 1,
  },

  // --- Week 12 Questions ---
  {
    week: 12,
    questionNumber: 1,
    text: "Redesigning business processes to increase organizational effectiveness is called:",
    options: ["Restructuring", "Reengineering", "Organizational Ethics", "Downsizing"],
    correctAnswer: "Reengineering",
    points: 1,
  },
  {
    week: 12,
    questionNumber: 2,
    text: "Revolutionary change happens slowly in an organization and on its own.",
    options: ["True", "False"],
    correctAnswer: "False",
    points: 1,
  },
  {
    week: 12,
    questionNumber: 3,
    text: "The formal system of task and authority relationships that control how people coordinate their actions and use resources to achieve organizational goals is called:",
    options: ["Organizational structure", "Organizational change", "Cognitive biases", "Resource allocation"],
    correctAnswer: "Organizational structure",
    points: 1,
  },
  {
    week: 12,
    questionNumber: 4,
    text: "Indian Railways having different zones of operation like Southern Railways, Central Railway etc. is an example of:",
    options: ["Horizontal differentiation", "Vertical differentiation", "Spatial differentiation", "None of the above"],
    correctAnswer: "Spatial differentiation",
    points: 1,
  },
  {
    week: 12,
    questionNumber: 5,
    text: "Defining employees' roles through formal documentation is a part of formalization.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },
  {
    week: 12,
    questionNumber: 6,
    text: "_______ can provide more inputs into decision making and will help in reducing information overload.",
    options: ["Centralization", "Decentralization", "Environmental uncertainty", "None of the above"],
    correctAnswer: "Decentralization",
    points: 1,
  },
  {
    week: 12,
    questionNumber: 7,
    text: "According to life-cycle perspective, the stage of organizational life cycle where the goals are ambiguous but there is a lot of creativity is called:",
    options: ["Formalization-and-control stage", "Collectivity stage", "Elaboration-of-structure stage", "Entrepreneurial stage"],
    correctAnswer: "Entrepreneurial stage",
    points: 1,
  },
  {
    week: 12,
    questionNumber: 8,
    text: "The life-cycle perspective sees the organization as an organism.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },
  {
    week: 12,
    questionNumber: 9,
    text: "A set of interrelated and interdependent parts arranged in a manner that produces a unified whole is called:",
    options: ["System", "Training", "Rituals", "Span of control"],
    correctAnswer: "System",
    points: 1,
  },
  {
    week: 12,
    questionNumber: 10,
    text: "Closed systems differentiate too much from the larger system and have their own identity.",
    options: ["True", "False"],
    correctAnswer: "True",
    points: 1,
  },
];

module.exports = questionsData;